In [1]:
import numpy as np
import pandas as pd

# Missing Data

A new pd.NA value (singleton) is introduced to represent scalar missing values. Up to now, pandas used several values to represent missing data: np.nan is used for this for float data, np.nan or None for object-dtype data and pd.NaT for datetime-like data. The goal of pd.NA is to provide a “missing” indicator that can be used consistently across data types. pd.NA is currently used by the nullable integer and boolean data types and the new string data type

In [2]:
np.nan

nan

In [3]:
pd.NA

In [4]:
pd.NaT

NaT

## Data

In [5]:
df = pd.read_csv('movie_scores.csv')

In [8]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

## Checking and Selecting for Null Values

In [14]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [15]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [16]:
df['first_name']

0      Tom
1      NaN
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

In [17]:
df['first_name'].notnull()

0     True
1    False
2     True
3     True
4     True
Name: first_name, dtype: bool

In [18]:
df[(df['pre_movie_score'].isnull()) & df['sex'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

## Drop Data

In [19]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [20]:
df.dropna()

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [30]:
#thresh : int, optional
#Require that many non-NA values.
# Keep only the rows with at least 2 non-NA values.
df.dropna(thresh=2)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [31]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [32]:
df.dropna(thresh=4,axis=1)

  first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

## Fill Data

In [33]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [34]:
df.fillna("NEW VALUE")

  first_name  last_name        age        sex pre_movie_score post_movie_score
0        Tom      Hanks       63.0          m             8.0             10.0
1  NEW VALUE  NEW VALUE  NEW VALUE  NEW VALUE       NEW VALUE        NEW VALUE
2       Hugh    Jackman       51.0          m       NEW VALUE        NEW VALUE
3      Oprah    Winfrey       66.0          f             6.0              8.0
4       Emma      Stone       31.0          f             7.0              9.0

In [35]:
df['first_name'].fillna("Empty")

0      Tom
1    Empty
2     Hugh
3    Oprah
4     Emma
Name: first_name, dtype: object

In [36]:
df['first_name'] = df['first_name'].fillna("Empty")

In [37]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1      Empty       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [38]:
df['pre_movie_score'].mean()

np.float64(7.0)

In [39]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [45]:
df.mean(numeric_only=True)

age                 52.75
pre_movie_score      7.00
post_movie_score     9.00
dtype: float64

In [46]:
df.fillna(df.mean(numeric_only=True))

  first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1      Empty       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

In [47]:
df['post_movie_score'].mean()

np.float64(9.0)