In [1]:
import numpy as np
import pandas as pd

# Combining DataFrames

## Concatenation

In [8]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']}

In [9]:
data_two = {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [10]:
one = pd.DataFrame(data_one)

In [11]:
two = pd.DataFrame(data_two)

In [12]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [13]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

## Axis = 0

### Concatenate along rows

In [15]:
axis0 = pd.concat([one, two], axis=0)

In [16]:
axis0

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

## Axis = 1

### Concatenate along columns

In [19]:
axis1 = pd.concat([one, two], axis=1)

In [20]:
axis1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

## Axis 0 , but columns match up

In [21]:
two.columns = one.columns

In [23]:
pd.concat([one, two])

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

## Merge

### Data Tables

In [27]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [28]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [29]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

## pd.merge()
Merge pandas DataFrames based on key columns, similar to a SQL join. Results based on the how parameter.

## Inner, Left, Right, and Outer Joins

### Inner Join
Match up where the **key is present in BOTH tables**. There should be no NaNs due to the join, since by definition to be part of the Inner Join they need info in both tables. Only Andrew and Bobo both registered and logged in.

In [35]:
# Notice pd.merge doesn't take in a list like concat
pd.merge(registrations,logins,how='inner',on='name')

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [36]:
# Pandas smart enough to figure out key column (on parameter) if only one column name matches up
pd.merge(registrations,logins,how='inner')

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [37]:
# Pandas reports an error if "on" key column isn't in both dataframes
#pd.merge(registrations,logins,how='inner',on='reg_id')

### Left Join
**Match up AND include all rows from Left Table**. Show everyone who registered on Left Table, if they don't have login info, then fill with NaN.

In [38]:
pd.merge(registrations, logins, how='left')

   reg_id    name  log_id
0       1  Andrew     2.0
1       2    Bobo     4.0
2       3  Claire     NaN
3       4   David     NaN

### Right Join
**Match up AND include all rows from Right Table**. Show everyone who logged in on the Right Table, if they don't have registration info, then fill with NaN.

In [41]:
pd.merge(registrations, logins, how='right')

   reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0     Bobo       4

### Outer Join
**Match up on all info found in either Left or Right Table**. Show everyone that's in the Log in table and the registrations table. Fill any missing info with NaN

In [42]:
pd.merge(registrations,logins,how='outer')

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0     Bobo     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0